### ISSUE TITLE
A tutorial for BioJupies Generator

### ISSUE THREAD

**Issue by zhilongjia** [MaayanLab/notebook-generator#1]
How to trigger the BioJupies Generator at GEO after I installed? So confused! A tutorial will be helpful. Thank you.

**Comment by denis-torre** [comment]
Hi @zhilongjia - apologies for the late reply.

The Chrome Extension automatically adds buttons below all available datasets in the GEO search pages. For example: [GSE88741](https://www.ncbi.nlm.nih.gov/gds/?term=GSE88741), [GSE105110](https://www.ncbi.nlm.nih.gov/gds/?term=GSE105110), [GSE107461](https://www.ncbi.nlm.nih.gov/gds/?term=GSE107461).  It currently supports ~4,200 RNA-seq datasets from mouse and human, so the buttons will only display for a subset of the search results.

A website with in-depth tutorials will be available in the next few weeks - I will add links to the README when they're ready. Feel free to let me know if you have any other issues.

**Comment by zhilongjia** [comment]
I just thought it's on the main page of a certain GSEid, such as https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE88741. 

As you said, Does it mean that the website had preprocessed the raw fq data, which is not related to group A&B labeling before a user clicked the notebook-generator button? Probably the release of ~4,200 RNA-seq list is helpful to users. Thank you.

**Comment by denis-torre** [comment]
Thanks for the suggestion - the button currently displays only in the search results, but we're planning to add it to landing pages soon.

The project relies on the data from ARCHS4, which contains publicly available data for 200,000+ processed FASTQ files from GEO. This data can be accessed at https://amp.pharm.mssm.edu/archs4/
